{"version":3,"status":"fail","tests":[{"name":"testFrom with data set #0","status":"error","test_code":"$date = $this->dateSetup($inputDate);\n$gs = from($date);\n\n$this->assertSame($expected, $gs->format('Y-m-d H:i:s'));\n","output":"Some output","message":"GigasecondTest::testFrom with data set #0\nBadFunctionCallException: Implement the from function\n\nGigasecond.php:6\nGigasecondTest.php:32"},{"name":"testFrom with data set #1","status":"error","test_code":"$date = $this->dateSetup($inputDate);\n$gs = from($date);\n\n$this->assertSame($expected, $gs->format('Y-m-d H:i:s'));\n","output":"Some output","message":"GigasecondTest::testFrom with data set #1\nBadFunctionCallException: Implement the from function\n\nGigasecond.php:6\nGigasecondTest.php:32"}]}
